version: '3'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
  product-service:
    build: ./product-service
    ports:
      - "5001:5000"